console.log("Try Catch Block")


//Syntax of Try Catch Block
// try{
//     console.log("In try Block")
// }
// catch{
//     console.log("In catch Block")
// }

//Example of try catch Block

let a =23,b=13;

try{
      console.log("The Addition is " ,a+b+c);
}catch{
    console.log("Error Occured");
}
finally{
    console.log("Finally Block")
}